baseURL = "https://mossplanet.com/"
languageCode = "ja-jp"
title = "mossplanet"
[pagination]
  pagerSize = 10

enableRobotsTXT = true

[params]
  tagline = "Illustration / Gamebook Portfolio"
  author = "モス / mossgray"
  description = "モスの作品ポートフォリオです。"
  twitter = "https://x.com/mossgray_"
  youtube = "https://www.youtube.com/@mossgray_"
  skeb = "https://skeb.jp/@mossgray_"
  email = "you@example.com"
  logo = "/images/logo/logo03.png"
  logoMobile = "/images/logo/logo03.png"
  heroImage = "/images/illust/hyoushi_animation.webp"
  profileImage = "/images/icons/profile.png"
  googleAnalytics = "G-FYDLVHFME8"

[menu]
  [[menu.main]]
    name = "Works"
    url = "/works/"
    weight = 10

[taxonomies]
  tag = "tags"
  category = "categories"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
